dubbo:
  application:
    name: consumer
  registry:
    address: 127.0.0.1:2181
    # zookeeperip
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    check:  false
    timeout: 3000

server:
  port: 8082

