server:
  port: 8081
  #当前服务/应用的名字
dubbo:
  application:
    name: provider

  #注册中心的协议和地址
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper

  #通信规则（通信协议和接口）
  protocol:
    name: dubbo
    port: 20880
  #连接监控中心
  monitor:
    protocol: registry
#开启包扫描，可替代 @EnableDubbo 注解
##dubbo.scan.base-packages=com.zang.gmall
